name: Terraform CI/CD

on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.0 # adapte si besoin

      - name: Configure Terraform to Skip Signature Check
        run: |
          echo '
          # Configuration pour résoudre les problèmes de clé PGP expirée pour les fournisseurs non-officiels.
          provider_installation {
            # Indique explicitement à Terraform de chercher sur le registre officiel.
            direct {}
          }
          ' > $HOME/.terraformrc

      - name: Terraform Init
        run: |
          rm -rf .terraform/ .terraform.lock.hcl
          terraform init -input=false

      - name: Terraform Plan
        run: terraform plan

      - name: Terraform Apply
        if: success()    # n'exécute que si le plan a réussi
        run: terraform apply -auto-approve

